/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class GameStartUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("GameStart");
        }
    }
    REG("ui.GameStartUI",GameStartUI);
}
export module ui.test {
    export class TestSceneUI extends Laya.Scene {
		public testScene_btn:Laya.Button;
		public btn_texttest:laya.display.Text;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/TestScene");
        }
    }
    REG("ui.test.TestSceneUI",TestSceneUI);
}
export module ui.UI {
    export class UIInGameUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("UI/UIInGame");
        }
    }
    REG("ui.UI.UIInGameUI",UIInGameUI);
    export class UIMainUI extends Laya.View {
		public testimge:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("UI/UIMain");
        }
    }
    REG("ui.UI.UIMainUI",UIMainUI);
}