/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameStart from "./script/GameStart"
import UIInGame from "./script/ui/UIInGame"
import UIMain from "./script/ui/UIMain"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1136;
    static height:number=640;
    static scaleMode:string="showall";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="UI/UIMain.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=false;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/GameStart.ts",GameStart);
        reg("script/ui/UIInGame.ts",UIInGame);
        reg("script/ui/UIMain.ts",UIMain);
    }
}
GameConfig.init();